// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6lWOpDTj060m8f1gsegtPkiyCn-Y4sM',
    appId: '1:167995437113:web:f3cb80deba0c4f9727dde8',
    messagingSenderId: '167995437113',
    projectId: 'locustaf-31ed2',
    authDomain: 'locustaf-31ed2.firebaseapp.com',
    storageBucket: 'locustaf-31ed2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQwFvCdTpMBMzFV8QehIpvDk05LJ1l5qQ',
    appId: '1:167995437113:android:4be8e71093afa94227dde8',
    messagingSenderId: '167995437113',
    projectId: 'locustaf-31ed2',
    storageBucket: 'locustaf-31ed2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzi8k8BX7Js998Bmh3JT3PrWjS9_M15-c',
    appId: '1:167995437113:ios:9e9a68f84e29d24b27dde8',
    messagingSenderId: '167995437113',
    projectId: 'locustaf-31ed2',
    storageBucket: 'locustaf-31ed2.firebasestorage.app',
    iosBundleId: 'com.example.appLocustaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzi8k8BX7Js998Bmh3JT3PrWjS9_M15-c',
    appId: '1:167995437113:ios:9e9a68f84e29d24b27dde8',
    messagingSenderId: '167995437113',
    projectId: 'locustaf-31ed2',
    storageBucket: 'locustaf-31ed2.firebasestorage.app',
    iosBundleId: 'com.example.appLocustaf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM6lWOpDTj060m8f1gsegtPkiyCn-Y4sM',
    appId: '1:167995437113:web:d76b2da6a25ad08427dde8',
    messagingSenderId: '167995437113',
    projectId: 'locustaf-31ed2',
    authDomain: 'locustaf-31ed2.firebaseapp.com',
    storageBucket: 'locustaf-31ed2.firebasestorage.app',
  );
}
